import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import type {Metadata} from 'next';
import {tomatoGrotesk} from '@/assets/fonts';
import Nav from '@/components/nav';
import Footer from '@/components/footer';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${tomatoGrotesk.className} min-h-screen bg-white px-4 lg:px-[25px] pt-2 pb-6 flex flex-col`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export {metadata};
